[workspace]
authors = ["Chris Fonnesbeck <fonnesbeck@gmail.com>"]
channels = ["conda-forge"]
name = "gssr-main"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
plotly = ">=6.2.0,<7"
ipykernel = ">=6.29.5,<7"
pymc = ">=5.23.0,<6"
polars = ">=1.31.0,<2"
jupyter = ">=1.1.1,<2"
pyarrow = ">=20.0.0,<21"
python-kaleido = ">=0.2.1,<0.3"
nbformat = ">=5.10.0,<6"
