[workspace]
authors = ["Chris Fonnesbeck <fonnesbeck@gmail.com>"]
channels = ["conda-forge"]
name = "Koenigsberg_Bayes"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"
plotly = ">=6.3.1,<7"
nutpie = ">=0.16.4,<0.17"
pyarrow = ">=22.0.0,<23"
graphviz = ">=14.1.0,<15"
pymc = "*"

